# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: notify

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn && yarn setup:remote # runs during prebuild
    command: echo 'Starting web development server (connected to staging API)' && yarn dev

github:
  prebuilds:
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
