# Dockerfile

# base image
FROM henrylec/yarn_berry:0.0.1

# # copy source files
WORKDIR /usr/src
COPY . .
# RUN yarn plugin import interactive-tools
# RUN ls
# # install dependencies
RUN yarn workspace @oasis/api install
RUN rm node_modules/next/dist/next-server/lib/router/router.d.ts

# start app
RUN yarn workspace @oasis/api run build
CMD yarn workspace @oasis/api run start
